### PR TITLE
Fix number entity units

### PR DESCRIPTION
**Pull request by mcolyer**
Fixed up tests and corrected the unit conversion.

### CODE REVIEW

**Review by filmkorn — APPROVED** [review]

**Comment by filmkorn** [comment]
@mcolyer Haven't tested it but looks good! 

I'm fixing up all the test in here: https://github.com/filmkorn/hacs-anova-nano/pull/2 but happy to rebase onto these changes.

**Comment by mcolyer** [comment]
I'd just merge this into your first pr and then I'll merge and we can follow up with that test pr when it's done.

**Comment by filmkorn** [comment]
Since your repo is the base, should we merge this PR into your main branch?

**Comment by mcolyer** [comment]
That works too.

**Pull request merged**
